branches:
  only:
  - master

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- chmod u+x ./build.sh
- chmod u+x ./publish.sh

script: "./build.sh"

after_success:
- "./publish.sh"

env:
  global:
  - secure: si0pDRg8Mjt5uQwzb2eK8wjoh/BtSh0QbJLTL3JmuCNQqIA/dw9qSDgY3W+SbZzdoPkIGfhaP+a46D726km8t7Z+fQTAWbT5M1pZtoOHF9Qesk4AEh3/s/gPRPlReYSQxAYA8fuAQ72H5zVhATLytIaD7LGYFEIHGTz7pbhBQyyMi72NFIK2/jG8tyXWnvKooX3fCBWthf2ihLFh9TyGdI2NniacKapwWPeSAtT/72RUXL4hc28275wdjuZOYpaTk5xrPaaMy8+TXTB9JmlY4INYZw3dW/1CAhpa4agLagvz8ENhPpuOfD/fxUfR/L6RUkvkcjpwj34zQC/6ikLwJ4D9OvkdhiPweU8ynHXXcyQBvxgO+qre8hQSGi3psFbb0N8xMWsXy5BT+Y9LkBdC6iuynl9emtK+NowzWX5RpuZ7vz10Gs7P5HP4ujQCGJUFvdSLHJxdYTTMLtXtQa8CxCReG/DAJz4r4CBIaaio+rHjoK6Ru4azVyYGm4rv+4BAl1lZNgFbBr6Am4RsYDV2EZsXhO49FvcO9zgJUOX4aEfW6XW2QzqC46r6VoHjhXxQVtyoksv6j8h1oHYZooXAwYe7hRCw34esJh4Mpgpm9bBvEEyaXjfQoZhZfJRvvXuLH4PXrYnft6Y5QLzKNndlnv6eKp2kPkpkjLlEjGZ+kig=
  - GH_USER_NAME: iliazeus
  - GH_PROJECT_NAME: law
  - GH_AUTHOR_NAME: Travis
  - GH_AUTHOR_EMAIL: noreply@travis.org
